# Generated by Django 3.0.6 on 2020-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={},
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='created',
        ),
        migrations.RemoveField(
            model_name='addresses',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='addresses',
            name='signup_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addresses',
            name='userid',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='addresses',
            name='userpw',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='name',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterModelTable(
            name='addresses',
            table='addresses',
        ),
    ]
