# Generated by Django 3.0.6 on 2020-06-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_pictures'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_picture', models.ImageField(upload_to='login')),
            ],
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='image'),
        ),
    ]
