# Generated by Django 3.0.6 on 2020-06-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20200611_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpicture',
            name='userid',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
