# Generated by Django 3.0.6 on 2020-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_loginpicture_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='picture',
        ),
        migrations.AddField(
            model_name='pictures',
            name='first_picture',
            field=models.ImageField(default=False, upload_to='image'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='second_picture',
            field=models.ImageField(default=False, upload_to='image'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='third_picture',
            field=models.ImageField(default=False, upload_to='image'),
        ),
        migrations.AddField(
            model_name='pictures',
            name='userid',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
